name: Update market JSONs

on:
  workflow_dispatch: {}
  schedule:
    # Twice on weekdays; adjust to taste
    - cron: "0 11 * * 1-5"
    - cron: "0 20 * * 1-5"

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch prices
        run: python scripts/fetch_prices.py

      - name: Commit changes (if any)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/data/prices_daily.json public/data/prices_monthly.json public/data/perf100_monthly.json
            git commit -m "Update prices JSONs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
