name: Update SP500 JSON
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * 1-5"  # weekdays 20:00 UTC
permissions:
  contents: write
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/fetch_sp500.py
      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/data/sp500.json
            git commit -m "Update sp500.json [skip ci]"
            git push
          fi
